#!/usr/bin/env bash
set -e

# get org name
org_name=$(git config remote.origin.url | cut -f4 -d'/')

# get repo name
repo_name=$(git config remote.origin.url | cut -f5 -d'/'|cut -f1 -d'.')

org_repo=$org_name/$repo_name

echo "--------------------------------------------------------------------------------"
echo -e "\e[1;31m Validating the repository - $org_name/$repo_name							\e[0m"
echo "--------------------------------------------------------------------------------"
echo " "

#Pass arguments through to another command
echo "1. Open issues:"
echo ""
gh issue list "$@" -R $org_repo

##Pass arguments through to another command
#echo "--------------------------------------------------------------------------------"
## Using the gh api command to retrieve and format information
# QUERY='
#   query($endCursor: String) {
#     viewer {
#       repositories(first: 100, after: $endCursor) {
#         nodes {
#           nameWithOwner
#           stargazerCount
#         }
#       }
#     }
#   }
# '
# TEMPLATE='
#   {{- range $repo := .data.viewer.repositories.nodes -}}
#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
#   {{- end -}}
# '
# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
#echo "--------------------------------------------------------------------------------"


echo " "
# check if README.md exists
echo "2. Checking if README is present																							"
FILE="README.md"
if [ ! -f "./$FILE" ]; then
    /usr/bin/printf "\u2717 $FILE doesn't exist\n"
else
    /usr/bin/printf "\xE2\x9C\x94 $FILE exists \n"
fi

echo " "
# check if .gitignore exists
echo "3. Checking if README is present																							"
FILE=".gitignore"
if [ ! -f "./$FILE" ]; then
    /usr/bin/printf "\u2717 $FILE doesn't exist\n"
else
    /usr/bin/printf "\xE2\x9C\x94 $FILE exists \n"
fi

echo " "
# check if workflow yaml exists
echo "4. Checking if workflow is present																							"
workflow_count=$(find . \( -name "*.yml" -o -name "*.yaml" \) | grep -i .github/workflows|wc -l)
if [ $workflow_count -ge 1 ]; then
    /usr/bin/printf "\xE2\x9C\x94 Workflow exists. Total Workflows found: $workflow_count \n"
else
    /usr/bin/printf "\u2717 Workflow doesn't exist\n"
fi

echo " "
# check if CODEOWNERS.md exists
echo "5. Checking if CODEOWNERS.md is present																							"
FILE="CODEOWNERS.md"
if [ ! -f "./$FILE" ]; then
    /usr/bin/printf "\u2717 $FILE doesn't exist\n"
else
    /usr/bin/printf "\xE2\x9C\x94 $FILE exists \n"
fi


